### ISSUE TITLE
Does not bring in highlight.js

### ISSUE THREAD

**Issue by elstamey** [demoneaux/reveal-code-focus#11]
I followed your install instructions for npm, but this isn't bringing in the `highlight.js`.  I think this used to be its own plugin, but I cannot find it.  

Can I bring the two .js files into my project and follow the dependency instructions from there?

**Comment by demoneaux** [comment]
Sorry for the really late response. As [mentioned in the slides](https://demoneaux.github.io/reveal-code-focus/#/2/1), the highlight.js library used should not be the Reveal plugin, but rather an actual copy of just the highlight.js library. Once it's loaded this plugin should be able to work.

**Comment by elstamey** [comment]
I did find that in the slides. I was following them in order and stopped
when I got stuck, before I saw that info.
