### ISSUE TITLE
Scroll to focused code

### ISSUE THREAD

**Issue by joshkel** [demoneaux/reveal-code-focus#6]
I wanted to use this plugin with a very long block of code, so I added a feature to scroll the focused lines' container to center the focused lines. You can view my work so far at https://github.com/joshkel/reveal-code-focus/tree/scrolling.

Would you be interested in this feature? I think it would be better if I added smooth scrolling and if I checked from a single boolean, defaulting to false, to an options object (with only the centerFocused option for now), defaulting to on, but I wanted to run the overall concept and design by you first.

**Comment by demoneaux** [comment]
This seems like a good idea. I can't review your code now, but maybe you can send a PR for the basic scroll functionality first.
